name: cyber-heist
region: nyc

services:
  - name: web
    # Build configuration
    build_command: npm install
    run_command: npm start
    
    # Environment
    environment_slug: node-js
    
    # GitHub integration
    github:
      repo: R4sammy/fun_friday
      branch: main
      deploy_on_push: true
    
    # HTTP configuration
    http_port: 3000
    
    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # Health check
    health_check:
      http_path: /
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Routes
    routes:
      - path: /
      - path: /socket.io
    
    # Environment variables
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
      - key: PORT
        value: "3000"
        scope: RUN_TIME
