name: cyber-heist
region: nyc

services:
  - name: web
    # Build configuration
    build_command: npm install
    run_command: npm start
    
    # Environment
    environment_slug: node-js
    
    # GitHub integration (update with your repo details)
    # Uncomment and configure when deploying from GitHub
    # github:
    #   repo: YOUR_USERNAME/cyber_hiest
    #   branch: main
    #   deploy_on_push: true
    
    # HTTP configuration
    http_port: 3000
    
    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # Health check
    health_check:
      http_path: /
    
    # Routes
    routes:
      - path: /
    
    # Environment variables (optional)
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
